/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DiagnosticianRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.Organizations.OrganizationDirectory;
import Business.Roles.LabAssistantRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientRegistrationRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * @author ajayp
 * @author nakul
 * @author palak
 *
 * Revision History:
 *
 * Date(MM/DD/YYYY) Author Comment 04/13/2021 @author nakul Added
 * DiagnosticCenter JPanel 04/14/2021 @author palak Added UserAccount, network
 */
public class DiagnosticianJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiagnosticianJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Network network;
    Enterprise enterprise;
    private OrganizationDirectory directory;

    public DiagnosticianJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.network = network;
        this.enterprise = enterprise;
        populateSamplesTable();
        populateLabAssistantCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageAssistant = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSamples = new javax.swing.JTable();
        lblAssignLabAssistant = new javax.swing.JLabel();
        comboLabAssistant = new javax.swing.JComboBox();
        btnSubmit = new javax.swing.JButton();

        lblManageAssistant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageAssistant.setText("Manage Lab Assistants");

        tblSamples.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Patient Name", "Symptoms", "Assigned Lab Assistant", "Created Date", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSamples);

        lblAssignLabAssistant.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblAssignLabAssistant.setText("Assign Lab Assistant");

        comboLabAssistant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSubmit.setText("Assign");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(lblManageAssistant, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAssignLabAssistant)
                                .addGap(39, 39, 39)
                                .addComponent(comboLabAssistant, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(btnSubmit)))))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblManageAssistant)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignLabAssistant)
                    .addComponent(comboLabAssistant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(166, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSamples.getSelectedRow();
        boolean isResolved = true;
        UserAccount empUserAccount = null;
        PatientRegistrationRequest patientRegistrationRequest = (PatientRegistrationRequest) tblSamples.getValueAt(selectedRow, 0);
        Employee labAssistant = (Employee) comboLabAssistant.getSelectedItem();
        if (selectedRow >= 0) {
            for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                for (UserAccount u : o.getUserAccountDirectory().getUserAccountList()) {
                    if (u.getEmployee().getId() == (labAssistant.getId())) {
                        empUserAccount = u;
                        break;
                    }
                }
            }
            }
            }
            for (WorkRequest wr : empUserAccount.getWorkQueue().getWorkRequestList()) {
                if (wr instanceof PatientRegistrationRequest) {
                    if (!((PatientRegistrationRequest) wr).getStatus().equals("Resolved")) {
                        isResolved = false;
                        break;
                    }
                }
            }
            if (isResolved) {
                String msg = JOptionPane.showInputDialog("Additional Information");
                patientRegistrationRequest.setLabAssistant(labAssistant);
                patientRegistrationRequest.setStatus("Assigned to Lab Assistant");
                patientRegistrationRequest.setMessage(msg);
                for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount u : o.getUserAccountDirectory().getUserAccountList()) {
                        if (u.getEmployee().getId() == (labAssistant.getId())) {
                            u.getWorkQueue().getWorkRequestList().add(patientRegistrationRequest);
                        }
                    }
                }
                JOptionPane.showMessageDialog(null, "Lab Assistant is assigned successfully");
                populateSamplesTable();
            } else {
                JOptionPane.showMessageDialog(null, "This lab assistant is already processing tests in Lab. Please select a different Lab Assistant.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Diadnostic Center to give your samples!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void populateSamplesTable() {
        DefaultTableModel samplesModel = (DefaultTableModel) tblSamples.getModel();
        samplesModel.setRowCount(0);
        System.out.println("enterprise" + enterprise);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HospitalEnterprise) {
                    for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
                        if (wr instanceof PatientRegistrationRequest) {
                            Object[] row = new Object[samplesModel.getColumnCount()];
                            row[0] = ((PatientRegistrationRequest) wr);
                            row[1] = ((PatientRegistrationRequest) wr).getPatientName();
                            row[2] = ((PatientRegistrationRequest) wr).getSymptom1();
                            row[3] = ((PatientRegistrationRequest) wr).getLabAssistant();
                            row[4] = ((PatientRegistrationRequest) wr).getRequestDate();
                            row[5] = ((PatientRegistrationRequest) wr).getStatus();
                            row[6] = ((PatientRegistrationRequest) wr).getMessage();
                            samplesModel.addRow(row);
                        }
                    }
                }
            }
        }
    }

    private void populateLabAssistantCombo() {
        comboLabAssistant.removeAllItems();
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount u : o.getUserAccountDirectory().getUserAccountList()) {
                        System.out.println(o.getUserAccountDirectory().getUserAccountList());
                        if (u.getRole() instanceof LabAssistantRole) {
                            comboLabAssistant.addItem(u.getEmployee());
                        }
                    }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboLabAssistant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAssignLabAssistant;
    private javax.swing.JLabel lblManageAssistant;
    private javax.swing.JTable tblSamples;
    // End of variables declaration//GEN-END:variables
}
