/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Roles.CareTakerRole;
import Business.Roles.DiagnosticianRole;
import Business.Roles.DoctorRole;
import Business.Roles.LabAssistantRole;
import Business.Roles.ManagerRole;
import Business.Roles.ManufacturerRole;
import Business.Roles.PharmacistRole;
import Business.Roles.SupplyChainRole;
import Business.UserAccount.UserAccount;
import Business.Utils.Validator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * @author ajayp
 * @author nakul
 * @author palak
 * 
 * Revision History:
 * 
 * Date(MM/DD/YYYY)      Author              Comment
 * 04/19/2021            @author palak      Added ManageEnterpriseAdminJPanel
 */

public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        populateTable();
        populateNetworkComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblNetwork = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox();
        lblEnterpriseType = new javax.swing.JLabel();
        comboEnterpriseType = new javax.swing.JComboBox();
        lblHospitalUsername1 = new javax.swing.JLabel();
        txtAdminName = new javax.swing.JTextField();
        lblHospitalUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblHospitalPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblenterprise = new javax.swing.JTable();
        btnSubmit = new javax.swing.JLabel();
        radioBtnManager = new javax.swing.JRadioButton();
        lblRole = new javax.swing.JLabel();
        radioBtnDiagnostician = new javax.swing.JRadioButton();
        radioBtnPharmacist = new javax.swing.JRadioButton();
        radioBtnManufacturer = new javax.swing.JRadioButton();
        radioBtnSupplyChain = new javax.swing.JRadioButton();
        radioBtnLabAssistant = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Enterprise Admin");

        lblNetwork.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblNetwork.setText("Network:");

        comboNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });

        lblEnterpriseType.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblEnterpriseType.setText("Enterprise Type:");

        comboEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEnterpriseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEnterpriseTypeActionPerformed(evt);
            }
        });

        lblHospitalUsername1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHospitalUsername1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHospitalUsername1.setText("Name:");

        txtAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminNameActionPerformed(evt);
            }
        });

        lblHospitalUsername.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHospitalUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHospitalUsername.setText("Username:");

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        lblHospitalPassword.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblHospitalPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHospitalPassword.setText("Password:");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblenterprise.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblenterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Name", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblenterprise);

        btnSubmit.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmit.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(25, 56, 82));
        btnSubmit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSubmit.setText("Create Enterprise Admin");
        btnSubmit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubmitMousePressed(evt);
            }
        });

        radioBtnManager.setText("Hospital Manager");
        radioBtnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnManagerActionPerformed(evt);
            }
        });

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblRole.setText("Role:");

        radioBtnDiagnostician.setText("Diagnostician");
        radioBtnDiagnostician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnDiagnosticianActionPerformed(evt);
            }
        });

        radioBtnPharmacist.setText("Pharmacist");
        radioBtnPharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPharmacistActionPerformed(evt);
            }
        });

        radioBtnManufacturer.setText("Manufacturer");
        radioBtnManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnManufacturerActionPerformed(evt);
            }
        });

        radioBtnSupplyChain.setText("Supply Chain");
        radioBtnSupplyChain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnSupplyChainActionPerformed(evt);
            }
        });

        radioBtnLabAssistant.setText("Lab Assistant");
        radioBtnLabAssistant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnLabAssistantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHospitalUsername1)
                                    .addComponent(lblEnterpriseType)
                                    .addComponent(lblNetwork))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(comboEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAdminName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHospitalPassword)
                                    .addComponent(lblHospitalUsername))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                    .addComponent(txtPassword)
                                    .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblRole, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnManager, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnDiagnostician, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(radioBtnPharmacist, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnManufacturer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnSupplyChain, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioBtnLabAssistant, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboEnterpriseType, comboNetwork});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPassword, txtUsername});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNetwork)
                    .addComponent(comboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole))
                .addGap(3, 3, 3)
                .addComponent(radioBtnManager)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEnterpriseType)
                            .addComponent(comboEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHospitalUsername1)
                            .addComponent(txtAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHospitalUsername)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHospitalPassword)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(radioBtnDiagnostician)
                        .addGap(7, 7, 7)
                        .addComponent(radioBtnLabAssistant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnPharmacist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnManufacturer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioBtnSupplyChain)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblenterprise.getModel();

        model.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[4];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getEmployee();
                    row[3] = userAccount.getUsername();
                    model.addRow(row);
                }
            }
        }
    }
     
    private void populateNetworkComboBox(){
        comboNetwork.removeAllItems();
        comboEnterpriseType.removeAllItems();
        
        for (Network network : ecosystem.getNetworkList()){
            comboNetwork.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        comboEnterpriseType.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            comboEnterpriseType.addItem(enterprise);
        }
    }
    
    private void txtAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminNameActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
       
    private void btnSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMousePressed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) comboEnterpriseType.getSelectedItem();

        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String name = txtAdminName.getText();
        
        if (!Validator.isValidUsername(username)) {
            JOptionPane.showMessageDialog(null, "Username is in incorrect \nFormat. Should be 2 to 25 characters "
                    + "and characters, numbers and the ., -, _ symbols");
            return;
        }
        
        if(!Validator.isValidPassword(password))
        {
            JOptionPane.showMessageDialog(null, "Password is in incorrect \nFormat. Should be minimum 8 in length "
                    + "with one upper case, one lower case, one digit and one special character");
            return;
        }
        
        if(username.isEmpty() || password.isEmpty() || name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all fields", "Warning", JOptionPane.WARNING_MESSAGE);
        } else{
            Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);

            if (ecosystem.checkIfUserIsUnique(username)) {
                UserAccount account = null;
                if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Hospital && radioBtnManager.isSelected()) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new ManagerRole());
                } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.DiagnosticCenter) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new DiagnosticianRole());
                } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Logistics) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new SupplyChainRole());
                } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.MedicalDeviceCompanies) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new ManufacturerRole());
                } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Pharmacy) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new PharmacistRole());
                }
                txtUsername.setText("");
                txtPassword.setText("");
                txtAdminName.setText("");
                radioBtnDiagnostician.setSelected(false);
                radioBtnManager.setSelected(false);
                radioBtnManufacturer.setSelected(false);
                radioBtnPharmacist.setSelected(false);
                radioBtnSupplyChain.setSelected(false);
                JOptionPane.showMessageDialog(null, "Account created sucessfully");
                populateTable();
            }else {
                JOptionPane.showMessageDialog(null, "Please enter unique username", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSubmitMousePressed

    private void radioBtnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnManagerActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManufacturer.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
    }//GEN-LAST:event_radioBtnManagerActionPerformed

    private void radioBtnDiagnosticianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnDiagnosticianActionPerformed
        // TODO add your handling code here:
        radioBtnManager.setSelected(false);
        radioBtnManufacturer.setSelected(false);
        radioBtnPharmacist.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
    }//GEN-LAST:event_radioBtnDiagnosticianActionPerformed

    private void radioBtnPharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPharmacistActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManufacturer.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
        radioBtnManager.setSelected(false);
    }//GEN-LAST:event_radioBtnPharmacistActionPerformed

    private void radioBtnManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnManufacturerActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManager.setSelected(false);
        radioBtnPharmacist.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
    }//GEN-LAST:event_radioBtnManufacturerActionPerformed

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed
        // TODO add your handling code here:
        Network network = (Network) comboNetwork.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_comboNetworkActionPerformed

    private void radioBtnSupplyChainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnSupplyChainActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManager.setSelected(false);
        radioBtnPharmacist.setSelected(false);
        radioBtnManufacturer.setSelected(false);
    }//GEN-LAST:event_radioBtnSupplyChainActionPerformed

    private void radioBtnLabAssistantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnLabAssistantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnLabAssistantActionPerformed

    private void comboEnterpriseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEnterpriseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEnterpriseTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JComboBox comboEnterpriseType;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblHospitalPassword;
    private javax.swing.JLabel lblHospitalUsername;
    private javax.swing.JLabel lblHospitalUsername1;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblRole;
    private javax.swing.JRadioButton radioBtnDiagnostician;
    private javax.swing.JRadioButton radioBtnLabAssistant;
    private javax.swing.JRadioButton radioBtnManager;
    private javax.swing.JRadioButton radioBtnManufacturer;
    private javax.swing.JRadioButton radioBtnPharmacist;
    private javax.swing.JRadioButton radioBtnSupplyChain;
    private javax.swing.JTable tblenterprise;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
