/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Roles.DiagnosticianRole;
import Business.Roles.LabAssistantRole;
import Business.Roles.ManagerRole;
import Business.Roles.ManufacturerRole;
import Business.Roles.PharmacistRole;
import Business.UserAccount.UserAccount;
import Business.Utils.Validator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * @author ajayp
 * @author nakul
 * @author palak
 * 
 * Revision History:
 * 
 * Date(MM/DD/YYYY)      Author              Comment
 * 04/23/2021            @author nakul      UI
 * 
 */

public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        populateTable();
        populateNetworkComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblNetwork = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox();
        lblEnterpriseType = new javax.swing.JLabel();
        comboEnterpriseType = new javax.swing.JComboBox();
        lblHospitalUsername1 = new javax.swing.JLabel();
        txtAdminName = new javax.swing.JTextField();
        lblHospitalUsername = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        lblHospitalPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblenterprise = new javax.swing.JTable();
        radioBtnManager = new javax.swing.JRadioButton();
        lblRole = new javax.swing.JLabel();
        radioBtnDiagnostician = new javax.swing.JRadioButton();
        radioBtnPharmacist = new javax.swing.JRadioButton();
        radioBtnManufacturer = new javax.swing.JRadioButton();
        radioBtnSupplyChain = new javax.swing.JRadioButton();
        radioBtnLabAssistant = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Enterprise Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 690, -1));

        lblNetwork.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNetwork.setText("Network:");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        comboNetwork.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        comboNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });
        add(comboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 320, -1));

        lblEnterpriseType.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblEnterpriseType.setText("Enterprise Type:");
        add(lblEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        comboEnterpriseType.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        comboEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 320, -1));

        lblHospitalUsername1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHospitalUsername1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHospitalUsername1.setText("Name:");
        add(lblHospitalUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        txtAdminName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdminNameActionPerformed(evt);
            }
        });
        add(txtAdminName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 320, 40));

        lblHospitalUsername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHospitalUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHospitalUsername.setText("Username:");
        add(lblHospitalUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSubmit.setText("Create Enterprise Admin");
        btnSubmit.setOpaque(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, 50));

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 320, 40));

        lblHospitalPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHospitalPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHospitalPassword.setText("Password:");
        add(lblHospitalPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 320, 40));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setOpaque(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 40));

        tblenterprise.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblenterprise.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblenterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Name", "Username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblenterprise.setRowHeight(50);
        jScrollPane3.setViewportView(tblenterprise);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 1190, 230));

        radioBtnManager.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radioBtnManager.setText("Hospital Manager");
        radioBtnManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnManagerActionPerformed(evt);
            }
        });
        add(radioBtnManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 250, -1));

        lblRole.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblRole.setText("Role:");
        add(lblRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, -1, -1));

        radioBtnDiagnostician.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radioBtnDiagnostician.setText("Diagnostician");
        radioBtnDiagnostician.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnDiagnosticianActionPerformed(evt);
            }
        });
        add(radioBtnDiagnostician, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        radioBtnPharmacist.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radioBtnPharmacist.setText("Pharmacist");
        radioBtnPharmacist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnPharmacistActionPerformed(evt);
            }
        });
        add(radioBtnPharmacist, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 200, 30));

        radioBtnManufacturer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radioBtnManufacturer.setText("Manufacturer");
        radioBtnManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnManufacturerActionPerformed(evt);
            }
        });
        add(radioBtnManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 210, 30));

        radioBtnSupplyChain.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radioBtnSupplyChain.setText("Supply Chain");
        radioBtnSupplyChain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnSupplyChainActionPerformed(evt);
            }
        });
        add(radioBtnSupplyChain, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 200, 40));

        radioBtnLabAssistant.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        radioBtnLabAssistant.setText("Lab Assistant");
        radioBtnLabAssistant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnLabAssistantActionPerformed(evt);
            }
        });
        add(radioBtnLabAssistant, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 200, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manageenterprise.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1950, 1000));
    }// </editor-fold>//GEN-END:initComponents

        private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblenterprise.getModel();

        model.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserAccountList()) {
                    Object[] row = new Object[4];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = userAccount.getEmployee();
                    row[3] = userAccount.getUsername();
                    model.addRow(row);
                }
            }
        }
    }
     
    private void populateNetworkComboBox(){
        comboNetwork.removeAllItems();
        comboEnterpriseType.removeAllItems();
        
        for (Network network : ecosystem.getNetworkList()){
            comboNetwork.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        comboEnterpriseType.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            comboEnterpriseType.addItem(enterprise);
        }
    }
    
    private void txtAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdminNameActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
       

    private void radioBtnManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnManagerActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManufacturer.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
        radioBtnLabAssistant.setSelected(false);
    }//GEN-LAST:event_radioBtnManagerActionPerformed

    private void radioBtnDiagnosticianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnDiagnosticianActionPerformed
        // TODO add your handling code here:
        radioBtnManager.setSelected(false);
        radioBtnManufacturer.setSelected(false);
        radioBtnPharmacist.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
        radioBtnLabAssistant.setSelected(false);
    }//GEN-LAST:event_radioBtnDiagnosticianActionPerformed

    private void radioBtnPharmacistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnPharmacistActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManufacturer.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
        radioBtnManager.setSelected(false);
        radioBtnLabAssistant.setSelected(false);
    }//GEN-LAST:event_radioBtnPharmacistActionPerformed

    private void radioBtnManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnManufacturerActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManager.setSelected(false);
        radioBtnPharmacist.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
        radioBtnLabAssistant.setSelected(false);
    }//GEN-LAST:event_radioBtnManufacturerActionPerformed

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed
        // TODO add your handling code here:
        Network network = (Network) comboNetwork.getSelectedItem();
        if (network != null){
            populateEnterpriseComboBox(network);
        }
    }//GEN-LAST:event_comboNetworkActionPerformed

    private void radioBtnSupplyChainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnSupplyChainActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManager.setSelected(false);
        radioBtnPharmacist.setSelected(false);
        radioBtnManufacturer.setSelected(false);
        radioBtnLabAssistant.setSelected(false);
    }//GEN-LAST:event_radioBtnSupplyChainActionPerformed

    private void radioBtnLabAssistantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnLabAssistantActionPerformed
        // TODO add your handling code here:
        radioBtnDiagnostician.setSelected(false);
        radioBtnManager.setSelected(false);
        radioBtnPharmacist.setSelected(false);
        radioBtnManufacturer.setSelected(false);
        radioBtnSupplyChain.setSelected(false);
    }//GEN-LAST:event_radioBtnLabAssistantActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) comboEnterpriseType.getSelectedItem();

        String username = txtUsername.getText();
        String password = String.valueOf(txtPassword.getPassword());
        String name = txtAdminName.getText();
        
        if (!Validator.isValidUsername(username)) {
            JOptionPane.showMessageDialog(null, "Username is in incorrect \nFormat. Should be 2 to 25 characters "
                    + "and characters, numbers and the ., -, _ symbols");
            return;
        }
        
        if(!Validator.isValidPassword(password))
        {
            JOptionPane.showMessageDialog(null, "Password is in incorrect \nFormat. Should be minimum 8 in length "
                    + "with one upper case, one lower case, one digit and one special character");
            return;
        }
        
        if(username.isEmpty() || password.isEmpty() || name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all fields", "Warning", JOptionPane.WARNING_MESSAGE);
        } else{
            Employee employee = enterprise.getEmployeeDirectory().createEmployee(name);

            if (ecosystem.checkIfUserIsUnique(username)) {
                UserAccount account = null;
                if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Hospital) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new ManagerRole());
                } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.DiagnosticCenter && radioBtnDiagnostician.isSelected()) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new DiagnosticianRole());
                } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.DiagnosticCenter && radioBtnLabAssistant.isSelected()) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new LabAssistantRole());
                } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.MedicalDeviceCompanies) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new ManufacturerRole());
                } else if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Pharmacy) {
                    account = enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new PharmacistRole());
                }
                txtUsername.setText("");
                txtPassword.setText("");
                txtAdminName.setText("");
                radioBtnDiagnostician.setSelected(false);
                radioBtnManager.setSelected(false);
                radioBtnManufacturer.setSelected(false);
                radioBtnPharmacist.setSelected(false);
                radioBtnSupplyChain.setSelected(false);
                JOptionPane.showMessageDialog(null, "Account created sucessfully");
                populateTable();
            }else {
                JOptionPane.showMessageDialog(null, "Please enter unique username", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboEnterpriseType;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblHospitalPassword;
    private javax.swing.JLabel lblHospitalUsername;
    private javax.swing.JLabel lblHospitalUsername1;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblRole;
    private javax.swing.JRadioButton radioBtnDiagnostician;
    private javax.swing.JRadioButton radioBtnLabAssistant;
    private javax.swing.JRadioButton radioBtnManager;
    private javax.swing.JRadioButton radioBtnManufacturer;
    private javax.swing.JRadioButton radioBtnPharmacist;
    private javax.swing.JRadioButton radioBtnSupplyChain;
    private javax.swing.JTable tblenterprise;
    private javax.swing.JTextField txtAdminName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
