/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.LabAssistantRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientRegistrationRequest;
import Business.WorkQueue.SendTestSampleRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajayp
 */
public class LabAssistantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabAssistantJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Network network;
    Enterprise enterprise;

    public LabAssistantJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.network = network;
        this.enterprise = enterprise;
        populateSamplesProcessTable();
        populateHospitalTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblManageSamples = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSamplesProcessed = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHospitals = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblManageSamples.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblManageSamples.setText("Manage Lab Samples");
        add(lblManageSamples, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 530, -1));

        tblSamplesProcessed.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblSamplesProcessed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Patient Name", "Samples", "Hospital Name", "Assigned Lab Assistant", "Diagnostics Center", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSamplesProcessed.setRowHeight(50);
        tblSamplesProcessed.setRowMargin(0);
        jScrollPane1.setViewportView(tblSamplesProcessed);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 1220, 240));

        btnAssign.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAssign.setText("Assign Hospital");
        btnAssign.setOpaque(false);
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 900, 230, 50));

        tblHospitals.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblHospitals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Hospital Name", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHospitals.setRowHeight(50);
        tblHospitals.setRowMargin(0);
        jScrollPane3.setViewportView(tblHospitals);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 610, 970, 240));

        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedHospitalRow = tblHospitals.getSelectedRow();
        int selectedSamplesRow = tblSamplesProcessed.getSelectedRow();
        PatientRegistrationRequest patientRegistrationRequest = (PatientRegistrationRequest) tblSamplesProcessed.getValueAt(selectedSamplesRow, 0);
        String hospitalName = (String) tblHospitals.getValueAt(selectedHospitalRow, 0);
        System.out.println("hospitalName" +hospitalName);
        if (selectedHospitalRow >= 0 && selectedSamplesRow >= 0) {
            String msg = JOptionPane.showInputDialog("Additional Information");
            patientRegistrationRequest.setHospitalName(hospitalName);
            patientRegistrationRequest.setStatus("Hospital Assigned");
            patientRegistrationRequest.setMessage(msg);
            JOptionPane.showMessageDialog(null, "Hospital Assignment Successful");
            populateSamplesProcessTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Hospital to send the samples!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void populateSamplesProcessTable() {
        DefaultTableModel samplesModel = (DefaultTableModel) tblSamplesProcessed.getModel();
        samplesModel.setRowCount(0);

        for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof PatientRegistrationRequest) {
                Object[] row = new Object[samplesModel.getColumnCount()];
                row[0] = ((PatientRegistrationRequest) wr);
                row[1] = ((PatientRegistrationRequest) wr).getPatientName();
                row[2] = ((PatientRegistrationRequest) wr).getSampleId();
                row[3] = ((PatientRegistrationRequest) wr).getHospitalName();
                row[4] = ((PatientRegistrationRequest) wr).getLabAssistant();
                row[5] = ((PatientRegistrationRequest) wr).getDiagnostician();
                row[6] = ((PatientRegistrationRequest) wr).getStatus();
                row[7] = ((PatientRegistrationRequest) wr).getMessage();
                samplesModel.addRow(row);
            }
        }
    }

    private void populateHospitalTable() {
        DefaultTableModel hospitalModel = (DefaultTableModel) tblHospitals.getModel();
        hospitalModel.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HospitalEnterprise) {
                    Object[] row = new Object[2];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    hospitalModel.addRow(row);
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblManageSamples;
    private javax.swing.JTable tblHospitals;
    private javax.swing.JTable tblSamplesProcessed;
    // End of variables declaration//GEN-END:variables
}
