/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 * @author ajayp
 * @author nakul
 * @author palak
 * 
 * Revision History:
 * 
 * Date(MM/DD/YYYY)      Author              Comment
 * 04/13/2021            @author nakul       Added DoctorWorkArea JPanel
 * 04/14/2021            @author palak       Added UserAccount, network
 */

public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount user;
    Network network;
    Enterprise enterprise;
    
    public DoctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount user, Network network, EcoSystem ecosystem, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.user = user;
        this.network = network;
        this.ecosystem=ecosystem;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblANewEnterprise = new javax.swing.JLabel();
        date_txt = new javax.swing.JLabel();
        time_txt = new javax.swing.JLabel();
        btnManagePrescriptions = new javax.swing.JButton();
        btnPatientPrescription = new javax.swing.JButton();
        btnAssignCareTaker = new javax.swing.JButton();

        lblANewEnterprise.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblANewEnterprise.setText("Welcome Doctor");

        date_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        time_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnManagePrescriptions.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnManagePrescriptions.setText("Manage Prescriptions");
        btnManagePrescriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePrescriptionsActionPerformed(evt);
            }
        });

        btnPatientPrescription.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPatientPrescription.setText("Manage Patient Prescriptions");
        btnPatientPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientPrescriptionActionPerformed(evt);
            }
        });

        btnAssignCareTaker.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnAssignCareTaker.setText("Manage Patients");
        btnAssignCareTaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignCareTakerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblANewEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(time_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnManagePrescriptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPatientPrescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAssignCareTaker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblANewEnterprise)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(time_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(btnManagePrescriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnPatientPrescription, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnAssignCareTaker, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePrescriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePrescriptionsActionPerformed
        // TODO add your handling code here:
        ManagePrescriptionsJPanel managePrescriptionsJPanel = new ManagePrescriptionsJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManagePrescriptionsJPanel", managePrescriptionsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePrescriptionsActionPerformed

    private void btnPatientPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientPrescriptionActionPerformed
        // TODO add your handling code here:
        ManagePatientPrescriptionJPanel managePatientPrescriptionJPanel = new ManagePatientPrescriptionJPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("ManagePatientPrescriptionJPanel", managePatientPrescriptionJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPatientPrescriptionActionPerformed

    private void btnAssignCareTakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignCareTakerActionPerformed
        // TODO add your handling code here:
        ManagePatientsJPanel managePatientsJPanel = new ManagePatientsJPanel(userProcessContainer, user, network, ecosystem, enterprise);
        userProcessContainer.add("ManagePatientsJPanel", managePatientsJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAssignCareTakerActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignCareTaker;
    private javax.swing.JButton btnManagePrescriptions;
    private javax.swing.JButton btnPatientPrescription;
    private javax.swing.JLabel date_txt;
    private javax.swing.JLabel lblANewEnterprise;
    private javax.swing.JLabel time_txt;
    // End of variables declaration//GEN-END:variables
}
