/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Medicine.Medicine;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.Organizations.PharmacyCatalogOrganization;
import Business.WorkQueue.MedicineWorkRequest;
import Business.WorkQueue.PatientRegistrationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author palak
 */
public class ManagePatientPrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientPrescriptionJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    private ArrayList<Medicine> medicienList;
    Enterprise enterpise;
    Organization organization;

    public ManagePatientPrescriptionJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Organization organization, Enterprise enterpise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.enterpise = enterpise;
        this.organization = organization;
        this.medicienList = new ArrayList<>();
        populatePatientTable();
        populateMedicine();
        populatePrescription();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void populatePatientTable() {
        DefaultTableModel samplesModel = (DefaultTableModel) tblPatientDetails.getModel();
        samplesModel.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HospitalEnterprise) {
                    for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
                        if (wr instanceof PatientRegistrationRequest) {
                            Object[] row = new Object[samplesModel.getColumnCount()];
                            row[0] = ((PatientRegistrationRequest) wr);
                            row[1] = ((PatientRegistrationRequest) wr).getPatientName();
                            row[2] = ((PatientRegistrationRequest) wr).getSymptom1();
                            row[3] = ((PatientRegistrationRequest) wr).getLabAssistant();
                            row[4] = ((PatientRegistrationRequest) wr).getCareTaker();
                            row[5] = ((PatientRegistrationRequest) wr).getRequestDate();
                            row[6] = ((PatientRegistrationRequest) wr).getStatus();
                            row[7] = ((PatientRegistrationRequest) wr).getMessage();
                            samplesModel.addRow(row);
                        }
                    }
                }
            }
        }
    }

    public void populateMedicine() {
        DefaultTableModel dtm = (DefaultTableModel) tblMedicine.getModel();
        dtm.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof PharmacyEnterprise) {
                    for (Medicine medicine : enterprise.getMedicineList()) {
                        Object[] row = new Object[dtm.getColumnCount()];
                        row[0] = medicine.getMedId();
                        row[1] = medicine;
                        dtm.addRow(row);
                    }
                }
            }
        }
    }

    public void populatePrescription() {
        DefaultTableModel dtm = (DefaultTableModel) tblPrescription.getModel();
        dtm.setRowCount(0);
        if (medicienList != null) {
            btnDeleteMed.setEnabled(true);
            btnConfirmMed.setEnabled(true);
            int count = 1;
            for (Medicine medicine : medicienList) {
                Object[] row = new Object[dtm.getColumnCount()];
                row[0] = count;
                row[1] = medicine;
                dtm.addRow(row);
                count++;
            }
        }
        if (tblPrescription.getRowCount() <= 0) {
            btnConfirmMed.setEnabled(false);
            btnDeleteMed.setEnabled(false);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();
        btnAddMedicine = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrescription = new javax.swing.JTable();
        btnDeleteMed = new javax.swing.JButton();
        btnConfirmMed = new javax.swing.JButton();
        lblManageAssistant = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPatientDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMedicine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine Id", "Medicine Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicine.setRowHeight(50);
        tblMedicine.setRowMargin(0);
        tblMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicineMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMedicine);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 670, 500, 220));

        btnAddMedicine.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddMedicine.setText("Add Medicine");
        btnAddMedicine.setOpaque(false);
        btnAddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicineActionPerformed(evt);
            }
        });
        add(btnAddMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 670, 240, 50));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setOpaque(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 110, 50));

        tblPrescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblPrescription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Medicine Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrescription.setRowHeight(50);
        tblPrescription.setRowMargin(0);
        jScrollPane1.setViewportView(tblPrescription);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, 460, 220));

        btnDeleteMed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDeleteMed.setText("Remove Medicine");
        btnDeleteMed.setOpaque(false);
        btnDeleteMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMedActionPerformed(evt);
            }
        });
        add(btnDeleteMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 840, -1, 50));

        btnConfirmMed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnConfirmMed.setText("Confirm Prescription");
        btnConfirmMed.setOpaque(false);
        btnConfirmMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmMedActionPerformed(evt);
            }
        });
        add(btnConfirmMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 920, -1, 50));

        lblManageAssistant.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblManageAssistant.setText("Prescribe Medicines to Patients");
        add(lblManageAssistant, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 760, -1));

        tblPatientDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblPatientDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Patient Name", "Symptoms", "Assigned Lab Assistant", "Assigned Care Taker", "Created Date", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatientDetails.setRowHeight(50);
        tblPatientDetails.setRowMargin(0);
        jScrollPane3.setViewportView(tblPatientDetails);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 390, 1250, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/doctorprescnew.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1440, 1080));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diagnew.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void tblMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicineMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblMedicine.getSelectedRow();
        if (selectedRow >= 0) {
            btnAddMedicine.setEnabled(true);
        }
    }//GEN-LAST:event_tblMedicineMouseClicked

    private void btnAddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMedicine.getSelectedRow();
        if (selectedRow >= 0) {
            Medicine medicine = (Medicine) tblMedicine.getValueAt(selectedRow, 1);
            medicienList.add(medicine);
            JOptionPane.showMessageDialog(null, "Medicine " + medicine.getMedName() + " added to cart successfully!");
            populatePrescription();
        } else {
            JOptionPane.showMessageDialog(null, "Please select Medicine to Add!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnAddMedicineActionPerformed

    private void btnDeleteMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMedActionPerformed
        // TODO add your handling code here:
        int selectedRow1 = tblPrescription.getSelectedRow();
        if (selectedRow1 >= 0) {
            Medicine medicine = (Medicine) tblPrescription.getValueAt(selectedRow1, 1);
            medicienList.remove(medicine);
            JOptionPane.showMessageDialog(null, "Medicine " + medicine.getMedName() + " removed from prescription Successfully!");
            populatePrescription();
        } else {
            JOptionPane.showMessageDialog(null, "Please select Medicine to remove!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

    }//GEN-LAST:event_btnDeleteMedActionPerformed

    private void btnConfirmMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmMedActionPerformed
        // TODO add your handling code here:
        int selectedPatientRow = tblPatientDetails.getSelectedRow();

        if (tblPrescription.getRowCount() >= 0 && selectedPatientRow >= 0) {
            PatientRegistrationRequest patientRegistrationRequest = (PatientRegistrationRequest) tblPatientDetails.getValueAt(selectedPatientRow, 0);
            String msg = JOptionPane.showInputDialog("Additional Information");
            MedicineWorkRequest medicineWorkRequest = new MedicineWorkRequest();
            medicineWorkRequest.setMedicineList(medicienList);
            medicineWorkRequest.setStatus("Prescribed");
            medicineWorkRequest.setMessage(msg);
            patientRegistrationRequest.setStatus("Prescribed");
            patientRegistrationRequest.setMessage(msg);

            organization.getWorkQueue().getWorkRequestList().add(medicineWorkRequest);
            JOptionPane.showMessageDialog(null, "Prescription submitted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            populatePatientTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select patient and add the medicines to the prescription.", "INFORMATION", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
    }//GEN-LAST:event_btnConfirmMedActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicine;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnConfirmMed;
    private javax.swing.JButton btnDeleteMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblManageAssistant;
    private javax.swing.JTable tblMedicine;
    private javax.swing.JTable tblPatientDetails;
    private javax.swing.JTable tblPrescription;
    // End of variables declaration//GEN-END:variables
}
