/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PharmacyWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Medicine.Medicine;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author palak
 */
public class ManageMedicinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageMedicinesJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Enterprise enterprise;

    public ManageMedicinesJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        populateMedicinetbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void populateMedicinetbl() {
        DefaultTableModel dtm = (DefaultTableModel) tblMedicine.getModel();
        dtm.setRowCount(0);
        for (Medicine medicine : enterprise.getMedicineList()) {
            Object row[] = new Object[2];
            row[0] = medicine;
            row[1] = medicine.getMedName();
            dtm.addRow(row);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblMedName = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitle.setText("Manage Medicine");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 430, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setOpaque(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, 50));

        lblMedName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMedName.setText("Medicine Name:");
        add(lblMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 250, 200, -1));

        txtMedName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 480, 30));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAdd.setText("Add Medicine");
        btnAdd.setOpaque(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 260, 40));

        tblMedicine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Medicine Id", "Medicine Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicine.setRowHeight(50);
        tblMedicine.setRowMargin(0);
        jScrollPane1.setViewportView(tblMedicine);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 470, 1060, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/presnew.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diagnew.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String medicineName = txtMedName.getText();
        if (medicineName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Medicine Name cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Medicine medicine = new Medicine(medicineName);
            enterprise.getMedicineList().add(medicine);
            JOptionPane.showMessageDialog(null, "Added Medicine Successfully");
            populateMedicinetbl();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblMedicine;
    private javax.swing.JTextField txtMedName;
    // End of variables declaration//GEN-END:variables
}
