/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PharmacyWorkArea;

/**
 *
 * @author ajayp
 */
public class ManagePharmacyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePharmacyJPanel
     */
    public ManagePharmacyJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManagePharmacy = new javax.swing.JLabel();
        btnManageMedicines = new javax.swing.JButton();
        btnManagePrescription = new javax.swing.JButton();

        lblManagePharmacy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManagePharmacy.setText("Manage Pharmacy");

        btnManageMedicines.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnManageMedicines.setText("Manage Medicines");

        btnManagePrescription.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnManagePrescription.setText("Manage Prescription");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblManagePharmacy))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManagePrescription)
                            .addComponent(btnManageMedicines))))
                .addContainerGap(323, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageMedicines, btnManagePrescription});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblManagePharmacy)
                .addGap(42, 42, 42)
                .addComponent(btnManageMedicines)
                .addGap(36, 36, 36)
                .addComponent(btnManagePrescription)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnManageMedicines, btnManagePrescription});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageMedicines;
    private javax.swing.JButton btnManagePrescription;
    private javax.swing.JLabel lblManagePharmacy;
    // End of variables declaration//GEN-END:variables
}
