/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PharmacyWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.WorkQueue.PatientRegistrationRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 * @author ajayp
 * @author nakul
 * @author palak
 * 
 * Revision History:
 * 
 * Date(MM/DD/YYYY)      Author              Comment
 * 04/13/2021            @author nakul       Added ManageMedicines JPanel
 * 04/14/2021            @author palak       Added UserAccount
 */
public class ManagePrescriptionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePrescriptionJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Enterprise enterprise;
    
    public ManagePrescriptionJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        populatePharmacistTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void populatePharmacistTable() {
        DefaultTableModel medicinesModel = (DefaultTableModel) tblProcessMedicines.getModel();
        medicinesModel.setRowCount(0);
        
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HospitalEnterprise) {
                    for (WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()) {
                        if (wr instanceof PatientRegistrationRequest) {
                            Object[] row = new Object[medicinesModel.getColumnCount()];
                            row[0] = ((PatientRegistrationRequest) wr);
                            row[1] = ((PatientRegistrationRequest) wr).getPatientName();
                            row[2] = ((PatientRegistrationRequest) wr).getDoctor();
                            row[3] = ((PatientRegistrationRequest) wr).getCareTaker();
                            row[4] = ((PatientRegistrationRequest) wr).getQuantity();
                            row[5] = ((PatientRegistrationRequest) wr).getStatus();
                            row[6] = ((PatientRegistrationRequest) wr).getMessage();
                            medicinesModel.addRow(row);
                        }
                    }
                }
            }
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedicinesToPatients = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProcessMedicines = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMedicinesToPatients.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblMedicinesToPatients.setText("Process the Medicines to Patients");
        add(lblMedicinesToPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 850, 70));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setOpaque(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, 50));

        tblProcessMedicines.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblProcessMedicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Doctor Name", "Care Taker Name", "No of Tablets", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProcessMedicines.setRowHeight(50);
        tblProcessMedicines.setRowMargin(0);
        jScrollPane1.setViewportView(tblProcessMedicines);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 1150, 240));

        btnProcess.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnProcess.setText("Process");
        btnProcess.setOpaque(false);
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 650, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/presnew.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diagnew.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProcessMedicines.getSelectedRow();
        
        if (selectedRow >= 0) {
            PatientRegistrationRequest patientRegistrationRequest = (PatientRegistrationRequest) tblProcessMedicines.getValueAt(selectedRow, 0);
                String msg = JOptionPane.showInputDialog("Additional Information");
                patientRegistrationRequest.setStatus("Medicines given to the Care Taker");
                patientRegistrationRequest.setMessage(msg);
                populatePharmacistTable();
        } else {
            JOptionPane.showMessageDialog(null, "Please select the prescription to given the medicines.");
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedicinesToPatients;
    private javax.swing.JTable tblProcessMedicines;
    // End of variables declaration//GEN-END:variables
}
