/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.Utils.Validator;
import Business.WorkQueue.PatientRegistrationRequest;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.util.Date;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * @author ajayp
 * @author nakul
 * @author palak
 * 
 * Revision History:
 * 
 * Date(MM/DD/YYYY)      Author              Comment
 * 04/15/2021            @author palak       Added Patient Registration Panel
 * 04/22/2021            @author palak       Updated JPanel
 */

public class PatientRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterprisesJPanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem ecosystem;
    Enterprise enterprise;
    
    public PatientRegistrationJPanel(JPanel userProcessContainer, EcoSystem ecosystem, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        populateOrganizationCombo();
        populateNetworkComboBox();
        radioBtnMale.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        lblPatientAge = new javax.swing.JLabel();
        txtPatientAge = new javax.swing.JTextField();
        lblPatientGender = new javax.swing.JLabel();
        radioBtnMale = new javax.swing.JRadioButton();
        radioBtnFemale = new javax.swing.JRadioButton();
        lblPatientUsername = new javax.swing.JLabel();
        txtPatientUsername = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblPatientPassword = new javax.swing.JLabel();
        txtPatientPassword = new javax.swing.JTextField();
        lblPatientAddress = new javax.swing.JLabel();
        txtPatientAddress = new javax.swing.JTextField();
        lblPatientNumber = new javax.swing.JLabel();
        txtPatientNumber = new javax.swing.JTextField();
        lblPatientSymptoms1 = new javax.swing.JLabel();
        txtPatientSymptoms1 = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lblPatientEmailId = new javax.swing.JLabel();
        txtPatientEmailId = new javax.swing.JTextField();
        lblNetwork = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox();
        comboOrganization = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Patient Registration Panel");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 690, -1));

        lblPatientName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientName.setText("Name : ");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 100, -1));

        txtPatientName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 440, 30));

        lblPatientAge.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientAge.setText("Age :");
        add(lblPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 100, -1));

        txtPatientAge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPatientAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

            }
        });
        add(txtPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 440, 30));

        lblPatientGender.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientGender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientGender.setText("Gender:");
        add(lblPatientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 130, -1));

        radioBtnMale.setText("Male");
        radioBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMaleActionPerformed(evt);
            }
        });
        add(radioBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 70, -1));

        radioBtnFemale.setText("Female");
        radioBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemaleActionPerformed(evt);
            }
        });
        add(radioBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, 80, -1));

        lblPatientUsername.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientUsername.setText("Username :");
        add(lblPatientUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 150, -1));

        txtPatientUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPatientUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 440, 30));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.setOpaque(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, 50));

        lblPatientPassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientPassword.setText("Password :");
        add(lblPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 150, -1));

        txtPatientPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 492, 440, 30));

        lblPatientAddress.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientAddress.setText("Address :");
        add(lblPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 160, -1));

        txtPatientAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 440, 30));

        lblPatientNumber.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientNumber.setText("Phone Number :");
        add(lblPatientNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        txtPatientNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPatientNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 440, 30));

        lblPatientSymptoms1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientSymptoms1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientSymptoms1.setText("Symptoms :");
        add(lblPatientSymptoms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 680, 190, -1));

        txtPatientSymptoms1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPatientSymptoms1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 690, 440, 30));

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setOpaque(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 780, 210, 50));

        lblPatientEmailId.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPatientEmailId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientEmailId.setText("Email Address :");
        add(lblPatientEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 190, -1));

        txtPatientEmailId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(txtPatientEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 540, 440, 30));

        lblNetwork.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNetwork.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNetwork.setText(" Network :");
        add(lblNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        comboNetwork.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        comboNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 352, 440, 30));

        comboOrganization.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        comboOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 440, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Organization Type : ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diagnew.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diagnew.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));
    }// </editor-fold>//GEN-END:initComponents

    private void populateOrganizationCombo(){
        comboOrganization.removeAllItems();
        for (Organization.Type type : Organization.Type.values()){
            if (!type.getValue().equals(Organization.Type.Admin.getValue()))
                comboOrganization.addItem(type);
        }
    }
      
    private void populateNetworkComboBox() {
        comboNetwork.removeAllItems();
        for (Network network : ecosystem.getNetworkList()) {
            comboNetwork.addItem(network);
        }
    }
        
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        Network network = (Network) comboNetwork.getSelectedItem();
        Organization.Type type = (Organization.Type) comboOrganization.getSelectedItem();
        
        String patientName = txtPatientName.getText();
        String patientAddress = txtPatientAddress.getText();
        String patientNumber = txtPatientNumber.getText();
        String patientUsername = txtPatientUsername.getText();
        String patientPassword = txtPatientPassword.getText();
        String patientSymptoms = txtPatientSymptoms1.getText();
        String patientAge      = txtPatientAge.getText();
        String patientEmailId  = txtPatientEmailId.getText();
        String sPatientGender  = "";
        boolean bSuccess = false;
        
        if (!Validator.isValidUsername(patientUsername)) {
            JOptionPane.showMessageDialog(null, "Username is in incorrect \nFormat. Should be 2 to 25 characters "
                    + "and characters, numbers and the ., -, _ symbols");
            return;
        }
        
        if(!Validator.isValidEmail(patientEmailId))
        {
            JOptionPane.showMessageDialog(null, "Email should be in correct format!"
                    + "\nFormat: abc@def.com");
            return;
        }
        
        if(!Validator.isValidPhoneNumber(patientNumber))
        {
            JOptionPane.showMessageDialog(null, "Contact Number should be in correct format!"
                    + "\nFormat: 10 digit Number or (Area Code)Number or +1 (Area Code)Number");
            return;
        }
        
        if(!Validator.isValidPassword(patientPassword))
        {
            JOptionPane.showMessageDialog(null, "Password is in incorrect \nFormat. Should be minimum 8 in length "
                    + "with one upper case, one lower case, one digit and one special character");
            return;
        }
        
        if(radioBtnMale.isSelected())
        {
            sPatientGender = radioBtnMale.getText();
        }
        else
        {
            sPatientGender = radioBtnFemale.getText();
        }
        
         if(patientName.isEmpty() || patientAddress.isEmpty() || patientNumber.isEmpty() || patientUsername.isEmpty() || patientPassword.isEmpty() || patientAge.isEmpty()
                 || patientSymptoms.isEmpty() || patientEmailId.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter all fields", "Warning", JOptionPane.WARNING_MESSAGE);
         } 
         else
         {
             String msg = JOptionPane.showInputDialog("Additional Information");
             
             
            PatientRegistrationRequest registrationRequest = new PatientRegistrationRequest();
            registrationRequest.setPatientName(patientName);
            registrationRequest.setPatientUsername(patientUsername);
            registrationRequest.setPatientPassword(patientPassword);
            registrationRequest.setPatientEmailId(patientEmailId);
            registrationRequest.setPatientAge(patientAge);
            registrationRequest.setPatientGender(sPatientGender);
            registrationRequest.setOrgType(type);
            registrationRequest.setNetwork(network);
            registrationRequest.setStatus("Requested");
            registrationRequest.setPatientNumber(patientNumber);
            registrationRequest.setPatientAddress(patientAddress);
            registrationRequest.setSymptom1(patientSymptoms);
            registrationRequest.setRequestDate(new Date());
            registrationRequest.setMessage(msg);
            sendEmailMessage(patientEmailId);

            for (Network network1 : ecosystem.getNetworkList()) {
                for (Enterprise enterprise : network1.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Hospital) {
                        if (enterprise.getWorkQueue() == null) {
                            enterprise.setWorkQueue(new WorkQueue());
                        }
                        enterprise.getWorkQueue().getWorkRequestList().add(registrationRequest);
                        bSuccess = true;
                    }
                }
            }

            if(bSuccess == true)
            {
                JOptionPane.showMessageDialog(null, "You have been registered succesfully!");
                txtPatientName.setText("");
                txtPatientUsername.setText("");
                txtPatientPassword.setText("");
                txtPatientAddress.setText("");
                txtPatientAge.setText("");
                txtPatientEmailId.setText("");
                txtPatientNumber.setText("");
                txtPatientSymptoms1.setText("");
                radioBtnFemale.setSelected(false);
                radioBtnMale.setSelected(false);
            }
            
         }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void radioBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemaleActionPerformed
        // TODO add your handling code here:
        radioBtnMale.setSelected(false);
    }//GEN-LAST:event_radioBtnFemaleActionPerformed

    private void radioBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMaleActionPerformed
        // TODO add your handling code here:
        radioBtnFemale.setSelected(false);
    }//GEN-LAST:event_radioBtnMaleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

public static void sendEmailMessage(String emailId) {
        // Recipient's email ID needs to be mentioned.
        String to = emailId;
        String from = "donotreplymobilization@gmail.com";
        String pass = "outbreakMobileSystem";
        // Assuming you are sending email from localhost
        // String host = "192.168.0.16";

        // Get system properties
        Properties properties = System.getProperties();
        String host = "smtp.gmail.com";

        properties.put("mail.smtp.starttls.enable", "true");

        properties.put("mail.smtp.ssl.trust", host);
        properties.put("mail.smtp.user", from);
        properties.put("mail.smtp.port", "587");
        properties.put("mail.smtp.auth", "true");

        Session session = Session.getDefaultInstance(properties);

        try {
            // Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

            // Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

            // Set To: header field of the header.
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

            // Set Subject: header field
            message.setSubject("Patient Registration");
            message.setText("Thank you for registering with us. Your account will be activated within 24 hours.\n After account activation, Please submit your samples to a Diagnostic Center.");
            // Send message
            Transport transport = session.getTransport("smtp");
            transport.connect(host, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();
            System.out.println("Sent message successfully....");
        } catch (MessagingException mex) {
            mex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Invalid email id");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JComboBox comboOrganization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientEmailId;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPatientNumber;
    private javax.swing.JLabel lblPatientPassword;
    private javax.swing.JLabel lblPatientSymptoms1;
    private javax.swing.JLabel lblPatientUsername;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton radioBtnFemale;
    private javax.swing.JRadioButton radioBtnMale;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPatientEmailId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPatientNumber;
    private javax.swing.JTextField txtPatientPassword;
    private javax.swing.JTextField txtPatientSymptoms1;
    private javax.swing.JTextField txtPatientUsername;
    // End of variables declaration//GEN-END:variables
}
