/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organizations.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 * @author ajayp
 * @author nakul
 * @author palak
 * 
 * Revision History:
 * 
 * Date(MM/DD/YYYY)      Author              Comment
 * 04/13/2021            @author nakul       Added PatientWorkArea JPanel
 * 04/14/2021            @author palak       Added UserAccount, network
 */

public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount user;
    Network network;
    Timer timer;
    Enterprise enterprise;
    Organization organization;
    
    public PatientWorkAreaJPanel(JPanel userProcessContainer,UserAccount user, Network network, EcoSystem ecosystem, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.user = user;
        this.network = network;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        this.organization = organization;
        
        ActionListener actionListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
                //Time in 12Hrs Format
                Date date1 = new Date();
                DateFormat timeFormat1 = new SimpleDateFormat("hh:mm:ss");
                String time1 = timeFormat1.format(date1);
                time_txt.setText(time1);
                
                //Todays Date
                Date date2 = new Date();
                DateFormat timeFormat2 = new SimpleDateFormat("MM/dd/yyyy");
                String time2 = timeFormat2.format(date2);
                date_txt.setText(time2);
            }
        };
        timer = new Timer(1000, actionListener);
        timer.setInitialDelay(0);
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblANewEnterprise = new javax.swing.JLabel();
        date_txt = new javax.swing.JLabel();
        time_txt = new javax.swing.JLabel();
        btnSampleTesting = new javax.swing.JButton();
        btnDrPrescription = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        date_txt1 = new javax.swing.JLabel();
        time_txt1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblANewEnterprise.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblANewEnterprise.setText("Welcome Patient");
        add(lblANewEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 460, -1));

        date_txt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 190, 30));

        time_txt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(time_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 50, 180, 30));

        btnSampleTesting.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSampleTesting.setText("Give Samples for Testing");
        btnSampleTesting.setOpaque(false);
        btnSampleTesting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSampleTestingActionPerformed(evt);
            }
        });
        add(btnSampleTesting, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 370, 50));

        btnDrPrescription.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnDrPrescription.setText("View Doctor Prescriptions");
        btnDrPrescription.setOpaque(false);
        btnDrPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrPrescriptionActionPerformed(evt);
            }
        });
        add(btnDrPrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 370, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/diagnew.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 1080));

        date_txt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(date_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 30, 180, 28));

        time_txt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        add(time_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1256, 30, 160, 28));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSampleTestingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSampleTestingActionPerformed
        // TODO add your handling code here:
        PatientSampleJPanel patientSampleJPanel = new PatientSampleJPanel(userProcessContainer, ecosystem, enterprise, organization);
        userProcessContainer.add("PatientSampleJPanel", patientSampleJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSampleTestingActionPerformed

    private void btnDrPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrPrescriptionActionPerformed
        // TODO add your handling code here:
        DoctorPrescriptionJPanel doctorPrescriptionJPanel = new DoctorPrescriptionJPanel(userProcessContainer, ecosystem, enterprise,user);
        userProcessContainer.add("DoctorPrescription", doctorPrescriptionJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDrPrescriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDrPrescription;
    private javax.swing.JButton btnSampleTesting;
    private javax.swing.JLabel date_txt;
    private javax.swing.JLabel date_txt1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblANewEnterprise;
    private javax.swing.JLabel time_txt;
    private javax.swing.JLabel time_txt1;
    // End of variables declaration//GEN-END:variables
}
