/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.LogisticsWorkArea;

import Business.EcoSystem;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

/**
 * @author ajayp
 * @author nakul
 * @author palak
 * 
 * Revision History:
 * 
 * Date(MM/DD/YYYY)      Author              Comment
 * 04/13/2021            @author nakul       Added ManageSupplyChain JPanel
 * 04/14/2021            @author palak       Added UserAccount and network
 */
public class ManageSupplyChainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSupplyChainJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount user;
    Network network;
    
    public ManageSupplyChainJPanel(JPanel userProcessContainer, UserAccount user, Network network, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.user = user;
        this.network = network;
        this.ecosystem=ecosystem;
        //populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        setLayout(new java.awt.BorderLayout());
=======
        lblManageSupplyChain = new javax.swing.JLabel();
        btnMedicalDevices = new javax.swing.JButton();
        btnMedicineDelivery = new javax.swing.JButton();

        lblManageSupplyChain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblManageSupplyChain.setText("Manage Logistics");

        btnMedicalDevices.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMedicalDevices.setText("Manage Medical Device");

        btnMedicineDelivery.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnMedicineDelivery.setText("Manage Pharmacy Medicines");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(lblManageSupplyChain))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMedicalDevices)
                            .addComponent(btnMedicineDelivery))))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMedicalDevices, btnMedicineDelivery});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblManageSupplyChain)
                .addGap(38, 38, 38)
                .addComponent(btnMedicineDelivery)
                .addGap(36, 36, 36)
                .addComponent(btnMedicalDevices)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnMedicalDevices, btnMedicineDelivery});

>>>>>>> 074ae50cae266db2381fc3ee61288d8ff3d66e84
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
=======
    private javax.swing.JButton btnMedicalDevices;
    private javax.swing.JButton btnMedicineDelivery;
    private javax.swing.JLabel lblManageSupplyChain;
>>>>>>> 074ae50cae266db2381fc3ee61288d8ff3d66e84
    // End of variables declaration//GEN-END:variables
}
